### PR TITLE
Added support for 'user_key' authentication mode in 'report' method

### PR DESCRIPTION
**Pull request by mayorova**
Closes https://github.com/3scale/3scale_ws_api_for_ruby/issues/20

### CODE REVIEW

**Comment by mikz** [comment]
Looks good to me. But the build fails. Maybe we should fix that first.

**Comment by mayorova** [comment]
Thanks for checking it out @mikz 
Not sure I can help with the failing build though...

**Comment by davidor** [comment]
I rebased on top of master.

The build is failing for all the ruby versions that Travis tries except 2.3.0. In the gemspec, there isn't a rack version specified, so Travis downloads the latest one (2.0.1), which requires ruby >= 2.2.2.

Master is currently failing for the same reason.

How to fix this: I think the ideal solution is to specify a minimum ruby version in the gemspec, and then, specify a rack version accordingly.

**Comment by davidor** [comment]
Merging this because the Travis error has nothing to do with the code introduced in this PR.
I've opened an issue to remind us to solve the problem: https://github.com/3scale/3scale_ws_api_for_ruby/issues/27

**Pull request merged**
